opencti:
  url: "http://localhost:8080"
  token: ""

connector:
  type: "EXTERNAL_IMPORT"
  id: "Luminar"
  name: "Luminar Threat Intelligence"
  scope: "identity,attack-pattern,malware,tool,report,vulnerability,campaign,incident,indicator,location,threat-actor,software,useraccount"
  log_level: "info"
  duration_period: "P2D" # Interval given for scheduler process in ISO-8601 format

luminar:
  base_url: ""
  account_id: ""
  client_id: ""
  client_secret: ""
  create_observable: True
  initial_fetch_date: ""

mq:
  host: 172.18.0.9
  port: 5672
  user: opencti
  pass: changeme